<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Sales\Block\Adminhtml\Order\View;

/**
 * @var Escaper $escaper
 * @var View $block
 */

$note = '';
$extensionAttributes = $block->getOrder()->getExtensionAttributes();
if ($extensionAttributes && $extensionAttributes->getCustomOrderNote()) {
    $note = $extensionAttributes->getCustomOrderNote()->getNote();
}
?>
<?php if ($note): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @noEscape */ __('Note') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item">
                <div class="admin__page-section-item-content">
                    <div class="order-payment-method-title">
                        <span><?= nl2br($escaper->escapeHtml($note)); ?></span>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
